# Generated by Django 3.2.13 on 2022-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_zone_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungalow',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cottage',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
