# Generated by Django 3.2.13 on 2022-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_zone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='service',
            name='subtype',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
